spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auth-service
              uri: http://${AUTH_SERVICE_HOST:localhost}:8080
              predicates:
                - Path=/api/auth/**
            - id: workspace-service
              uri: http://${AUTH_SERVICE_HOST:localhost}:8080
              predicates:
                - Path=/api/workspaces/**
            - id: ai-service
              uri: http://${AUTH_SERVICE_HOST:localhost}:8080
              predicates:
                - Path=/api/ai/**
            - id: task-service
              uri: http://${AUTH_SERVICE_HOST:localhost}:8080
              predicates:
                - Path=/api/projects/**
            - id: notification-service
              uri: http://${NOTIFICATION_SERVICE_HOST:localhost}:8081
              predicates:
                - Path=/api/notifications/**
            - id: analytics-service
              uri: http://${ANALYTICS_SERVICE_HOST:localhost}:8001
              predicates:
                - Path=/analytics/**

server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: health,gateway
