name: CI Pipeline
on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: taskflow
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
    env:
      JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      GROQ_API_KEY: dummy-key-not-set
      AWS_ACCESS_KEY_ID: dummy-key
      AWS_SECRET_ACCESS_KEY: dummy-secret
      AWS_REGION: ap-south-1
      AWS_S3_BUCKET: taskflow-attachments-ansh14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { java-version: '21', distribution: 'temurin' }
      - uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      - name: Test auth-service
        working-directory: ./auth-service
        run: ./mvnw test
      - name: Build auth-service
        working-directory: ./auth-service
        run: ./mvnw package -DskipTests
